name: space_rocket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/stars_0.png
    - assets/images/stars_1.png
    - assets/images/stars_2.png
    - assets/images/bullet.png
    - assets/images/enemy.png
    - assets/images/explosion.png
    - assets/images/player.png
